from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(591, 298)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(290, 10, 291, 221))
        self.groupBox.setStyleSheet("")
        self.groupBox.setObjectName("groupBox")
        self.epochs_ = QtWidgets.QSpinBox(self.groupBox)
        self.epochs_.setGeometry(QtCore.QRect(130, 140, 151, 31))
        self.epochs_.setMaximum(999)
        self.epochs_.setProperty("value", 100)
        self.epochs_.setObjectName("epochs_")
        self.optimizer_ = QtWidgets.QComboBox(self.groupBox)
        self.optimizer_.setGeometry(QtCore.QRect(130, 20, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.optimizer_.setFont(font)
        self.optimizer_.setObjectName("optimizer_")
        self.optimizer_.addItem("")
        self.optimizer_.addItem("")
        self.optimizer_.addItem("")
        self.optimizer_.addItem("")
        self.batchsize = QtWidgets.QSpinBox(self.groupBox)
        self.batchsize.setGeometry(QtCore.QRect(130, 100, 151, 31))
        self.batchsize.setMaximum(999999)
        self.batchsize.setProperty("value", 512)
        self.batchsize.setObjectName("batchsize")
        self.savepath = QtWidgets.QLineEdit(self.groupBox)
        self.savepath.setGeometry(QtCore.QRect(130, 180, 121, 31))
        self.savepath.setObjectName("savepath")
        self.savepath.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dir_choose = QtWidgets.QPushButton(self.groupBox)
        self.dir_choose.setGeometry(QtCore.QRect(250, 180, 31, 31))
        self.dir_choose.setText("")
        self.dir_choose.setObjectName("dir_choose")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(10, 20, 111, 31))
        self.label_7.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(10, 60, 111, 31))
        self.label_8.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(10, 100, 111, 31))
        self.label_9.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(10, 140, 111, 31))
        self.label_10.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(10, 180, 111, 31))
        self.label_11.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_11.setObjectName("label_11")
        self.lr2 = QtWidgets.QSpinBox(self.groupBox)
        self.lr2.setGeometry(QtCore.QRect(200, 60, 81, 31))
        self.lr2.setSuffix("")
        self.lr2.setProperty("value", 4)
        self.lr2.setObjectName("lr2")
        self.lr1 = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.lr1.setGeometry(QtCore.QRect(130, 60, 70, 31))
        self.lr1.setMinimum(1.0)
        self.lr1.setMaximum(9.99)
        self.lr1.setSingleStep(0.01)
        self.lr1.setProperty("value", 1.0)
        self.lr1.setObjectName("lr1")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 150, 271, 141))
        self.groupBox_2.setStyleSheet("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(10, 20, 101, 31))
        self.label_4.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(10, 60, 101, 31))
        self.label_5.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(10, 100, 101, 31))
        self.label_6.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_6.setObjectName("label_6")
        self.startshift = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.startshift.setGeometry(QtCore.QRect(110, 20, 151, 31))
        self.startshift.setMaximum(99999.99)
        self.startshift.setSingleStep(0.01)
        self.startshift.setProperty("value", 240.0)
        self.startshift.setObjectName("startshift")
        self.endshift = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.endshift.setGeometry(QtCore.QRect(110, 60, 151, 31))
        self.endshift.setMaximum(99999.99)
        self.endshift.setSingleStep(0.01)
        self.endshift.setProperty("value", 2000.0)
        self.endshift.setObjectName("endshift")
        self.interval = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.interval.setGeometry(QtCore.QRect(110, 100, 151, 31))
        self.interval.setMaximum(99999.99)
        self.interval.setSingleStep(0.01)
        self.interval.setProperty("value", 2.0)
        self.interval.setObjectName("interval")
        self.save_ = QtWidgets.QPushButton(Dialog)
        self.save_.setEnabled(False)
        self.save_.setGeometry(QtCore.QRect(310, 250, 93, 28))
        self.save_.setObjectName("save_")
        self.cancel_ = QtWidgets.QPushButton(Dialog)
        self.cancel_.setGeometry(QtCore.QRect(450, 250, 93, 28))
        self.cancel_.setObjectName("cancel_")
        self.groupBox_4 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 10, 271, 141))
        self.groupBox_4.setObjectName("groupBox_4")
        self.number = QtWidgets.QSpinBox(self.groupBox_4)
        self.number.setGeometry(QtCore.QRect(110, 20, 151, 31))
        self.number.setMaximum(999999)
        self.number.setProperty("value", 30000)
        self.number.setObjectName("number")
        self.aug_choose = QtWidgets.QPushButton(self.groupBox_4)
        self.aug_choose.setGeometry(QtCore.QRect(230, 100, 31, 31))
        self.aug_choose.setText("")
        self.aug_choose.setObjectName("aug_choose")
        self.aug_savepath = QtWidgets.QLineEdit(self.groupBox_4)
        self.aug_savepath.setGeometry(QtCore.QRect(110, 100, 121, 31))
        self.aug_savepath.setObjectName("aug_savepath")
        self.aug_savepath.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label = QtWidgets.QLabel(self.groupBox_4)
        self.label.setGeometry(QtCore.QRect(10, 20, 101, 31))
        self.label.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 101, 31))
        self.label_2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_4)
        self.label_3.setGeometry(QtCore.QRect(10, 100, 101, 31))
        self.label_3.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_3.setObjectName("label_3")
        self.noise2 = QtWidgets.QSpinBox(self.groupBox_4)
        self.noise2.setGeometry(QtCore.QRect(180, 60, 81, 31))
        self.noise2.setSuffix("")
        self.noise2.setProperty("value", 3)
        self.noise2.setObjectName("noise2")
        self.noise1 = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.noise1.setGeometry(QtCore.QRect(110, 60, 70, 31))
        self.noise1.setMinimum(1.0)
        self.noise1.setMaximum(9.99)
        self.noise1.setSingleStep(0.01)
        self.noise1.setProperty("value", 5.0)
        self.noise1.setObjectName("noise1")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Parameter"))
        self.groupBox.setTitle(_translate("Dialog", "Training"))
        self.optimizer_.setItemText(0, _translate("Dialog", "Adam"))
        self.optimizer_.setItemText(1, _translate("Dialog", "Adadelta"))
        self.optimizer_.setItemText(2, _translate("Dialog", "Adagrad"))
        self.optimizer_.setItemText(3, _translate("Dialog", "Adamax"))
        self.label_7.setText(_translate("Dialog", "optimizer"))
        self.label_8.setText(_translate("Dialog", "learning rate"))
        self.label_9.setText(_translate("Dialog", "batch size"))
        self.label_10.setText(_translate("Dialog", "epochs"))
        self.label_11.setText(_translate("Dialog", "models path"))
        self.lr2.setPrefix(_translate("Dialog", "e-"))
        self.groupBox_2.setTitle(_translate("Dialog", "Raman Shift"))
        self.label_4.setText(_translate("Dialog", "Start"))
        self.label_5.setText(_translate("Dialog", "End"))
        self.label_6.setText(_translate("Dialog", "Interval"))
        self.save_.setText(_translate("Dialog", "save"))
        self.cancel_.setText(_translate("Dialog", "cancel"))
        self.groupBox_4.setTitle(_translate("Dialog", "Data Augmentation"))
        self.label.setText(_translate("Dialog", "Number"))
        self.label_2.setText(_translate("Dialog", "Noise Rate"))
        self.label_3.setText(_translate("Dialog", "Save Path"))
        self.noise2.setPrefix(_translate("Dialog", "e-"))